### ISSUE TITLE
Satterthwaite method fails for binomial model

### ISSUE THREAD

**Issue by Benambridge** [runehaubo/lmerTestR#29]
Hi

I'm trying to fit this model using lmerTest, but it fails (i.e., summary just outputs the normal lme4 p values from the z distribution, presumably meaning it has failed to calculated the Satterthwaite df):

Full1=glmer(correct ~ MLU + BPVS_raw + Chi_Dir_Log*group*condition + (1+Chi_Dir_Log|Participant) + (1|item), data=Data, family=binomial, glmerControl(optimizer = "bobyqa")) 

Is there a problem using the Satterthwaite method for binomial models, or is it something else?

Thanks
Ben

**Comment by runehaubo** [comment]
Satterthwaite aids the F-test in the multivariate normal distribution that
arises in the linear mixed models. Since similar F-tests are not defined
for non-normal outcomes the method can only be applied for LMMs.

Cheers
Rune

ons. 23. okt. 2019 kl. 10.04 skrev Benambridge <notifications@github.com>:
