### ISSUE TITLE
Perform one-tailed tests with lmerTest

### ISSUE THREAD

**Issue by HaiyangJin** [runehaubo/lmerTestR#42]
Dear authors,

I wonder if there is a way to perform one-tailed tests with lmerTest? I cannot find a solution by checking the help files. 

Thanks in advance,
Haiyang

**Comment by runehaubo** [comment]
I suppose you would do it in the same way that you would do it with the results of `lm` or `glm`, say. That is, I don't see that your question is special to `lmerTest`. However, since the summary function returns t-values and the df for all coefficients, you can compute the p-value of any hypothesis you are most interested in yourself.
